I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 124, in script
    楓原"待つでござる。お主GeoGebraで複素数平面を扱う方法を知ってるでござるか？"
Exception: Sayer '楓原' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 124, in script
    楓原"待つでござる。お主GeoGebraで複素数平面を扱う方法を知ってるでござるか？"
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer '楓原' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.1.24090601
VisualNovel_Programming 1.0
Sun Jan 26 00:27:43 2025
